update zh-Hant.json
xanderfrangos/twinkle-tray pull request #481
Opened 2022-11-10 10:00 UTC by 5idereal

2022-11-21 05:14 UTC, wc7086 requested changes

2022-11-21 05:14 UTC, wc7086 commented on src/localization/zh-Hant.json
> +    "SETTINGS_MONITORS_HIDE_DISPLAYS_DESC": "如果您想要從彈出視窗中隱藏指定的顯示器，您可以在此設定。",
`SETTINGS_MONITORS_HIDE_DISPLAYS_TITLE`和`SETTINGS_MONITORS_HIDE_DISPLAYS_DESC`应在`SETTINGS_MONITORS_HIDE_INTERNAL_TITLE`前面。

2022-11-23 04:31 UTC, 5idereal commented on src/localization/zh-Hant.json
> +    "SETTINGS_MONITORS_HIDE_DISPLAYS_DESC": "如果您想要從彈出視窗中隱藏指定的顯示器，您可以在此設定。",
您好，我是按 en.json 的順序排列的。方便詢問下您的排序依據是？

2022-11-24 14:35 UTC, wc7086 commented on src/localization/zh-Hant.json
> +    "SETTINGS_MONITORS_HIDE_DISPLAYS_DESC": "如果您想要從彈出視窗中隱藏指定的顯示器，您可以在此設定。",
> 您好，我是按 en.json 的順序排列的。方便詢問下您的排序依據是？

不好意思，我排序时没注意 en.json 的版本，查看的是旧 commit 的 en.json。你的排序是正确的，这个 pr 可以合并了。

2022-11-27 20:03 UTC, wc7086 commented
@xanderfrangos please merge this pull requests
https://github.com/xanderfrangos/twinkle-tray/pull/497#issue-1463450554

2022-11-27 20:03 UTC, merged